cageMaterial: RED_STAINED_GLASS
cageSize: 4
# The larger the number, the better the performance,
# but it should be smaller than the size.
movementToMoveCage: 3
# More efficient if true
skipEdges: true

logCageCreation: true